# Generated by Django 5.0.2 on 2024-05-18 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_helprequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
