# Generated by Django 5.0.2 on 2024-05-18 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_manager_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='is_available',
            field=models.CharField(choices=[('Available', 'Available'), ('Not-Available', 'Not-Available')], default='Available', max_length=13),
        ),
    ]
