# Generated by Django 5.0.2 on 2024-05-18 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_manager_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='phone_number',
            field=models.BigIntegerField(max_length=10),
        ),
    ]
