# Generated by Django 5.0.2 on 2024-05-18 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_manager_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='phone_number',
            field=models.BigIntegerField(),
        ),
    ]
